const fallbackQuotes = [
  { content: "Build something today that yesterday's you would be proud of.", author: "M. Reeves" },
  { content: "The best code is the code you never have to debug twice.", author: "S. Chen" },
  { content: "Every blank page is a chance to start something new.", author: "J. Torres" },
  { content: "Progress over perfection. Ship it, then improve it.", author: "A. Patel" },
  { content: "Your future self will thank you for the small steps you take today.", author: "L. Okonkwo" },
  { content: "The only bad idea is the one you never try.", author: "R. Kim" },
  { content: "Rest is not laziness. It's part of the work.", author: "E. Vasquez" },
  { content: "Learn one thing deeply before chasing ten things shallowly.", author: "D. Foster" },
  { content: "The obstacle is often the path.", author: "N. Walsh" },
  { content: "Create with your hands. Think with your heart.", author: "T. Nakamura" },
  { content: "Done is better than perfect. Perfect is the enemy of done.", author: "K. O'Brien" },
  { content: "Your curiosity is your compass. Follow it.", author: "M. Santos" },
  { content: "The best time to fix a bug was when you wrote it. The second best time is now.", author: "P. Rivera" },
  { content: "Small wins compound into big victories.", author: "H. Zhang" },
  { content: "You don't need permission to start. You need courage.", author: "F. Adeyemi" },
  { content: "The blank canvas is not empty. It's full of possibility.", author: "C. Morrison" },
  { content: "Build in public. Learn in private.", author: "V. Kozlov" },
  { content: "Every expert was once a beginner who kept going.", author: "B. Thompson" },
  { content: "Simplify until it hurts. Then simplify one more time.", author: "Y. Tanaka" },
  { content: "The best tool is the one you actually use.", author: "G. Schmidt" },
  { content: "Make things that matter to at least one person. Start with yourself.", author: "I. Hassan" },
  { content: "Feedback is a gift. Even when it stings.", author: "O. Williams" },
  { content: "Write for humans first. Machines second.", author: "U. Ahmed" },
  { content: "The best way to learn is to teach. The best way to teach is to build.", author: "Q. Liu" },
  { content: "Start before you're ready. You'll never feel ready.", author: "W. Park" },
  { content: "Your taste will outpace your skill. That's how you grow.", author: "Z. Morgan" },
  { content: "Consistency beats intensity. Show up every day.", author: "X. Rodriguez" },
  { content: "The problem you avoid today becomes the crisis you face tomorrow.", author: "J. Ellis" },
  { content: "Build something you wish existed.", author: "R. Hayes" },
  { content: "Clarity comes from doing, not from thinking about doing.", author: "S. Kumar" },
  { content: "The best apology is changed behavior.", author: "T. Nguyen" },
  { content: "You are not your code. You are the person who keeps improving.", author: "A. Brooks" },
  { content: "Delete more than you add. Less is almost always more.", author: "E. Jensen" },
  { content: "The right question is worth a hundred wrong answers.", author: "L. Costa" },
  { content: "Ship fast. Iterate faster. Listen always.", author: "M. Okello" },
  { content: "Your past projects are not failures. They're lessons with names.", author: "N. Fischer" },
  { content: "The best collaboration happens when everyone feels safe to be wrong.", author: "P. Webb" },
  { content: "Automate the boring stuff. Focus on the human stuff.", author: "K. Singh" },
  { content: "Read the docs. Then read them again.", author: "H. Martinez" },
  { content: "The code you write today is a message to your future self. Be kind.", author: "F. Okafor" },
  { content: "Celebrate the small wins. They add up.", author: "C. Wright" },
  { content: "The best design is invisible. It just works.", author: "V. Petrov" },
  { content: "Ask for help. Give help. Repeat.", author: "B. Johnson" },
  { content: "Your inbox is not your to-do list. Your to-do list is your to-do list.", author: "Y. Chen" },
  { content: "The only way out is through. The only way through is one step at a time.", author: "G. Taylor" },
  { content: "Build for the user you were yesterday.", author: "I. Rahman" },
  { content: "Sleep on it. The best ideas come when you're not forcing them.", author: "O. Silva" },
  { content: "Your first draft is allowed to be bad. That's why it's called a draft.", author: "U. Patel" },
  { content: "The best time to document is while you still remember why you built it.", author: "Q. Anderson" },
  { content: "Comparison is the thief of joy. Compare yourself to who you were yesterday.", author: "W. Davis" },
];
