const fallbackQuotes = [
  { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { content: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { content: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { content: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { content: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { content: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { content: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { content: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { content: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { content: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { content: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { content: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { content: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { content: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { content: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { content: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { content: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { content: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { content: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { content: "When one door of happiness closes, another opens.", author: "Helen Keller" },
  { content: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { content: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
  { content: "The mind is everything. What you think you become.", author: "Buddha" },
  { content: "The best revenge is massive success.", author: "Frank Sinatra" },
  { content: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { content: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Act as if what you do makes a difference. It does.", author: "William James" },
  { content: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { content: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey" },
  { content: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
  { content: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { content: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { content: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { content: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { content: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
  { content: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { content: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { content: "Nothing is impossible. The word itself says 'I'm possible!'", author: "Audrey Hepburn" },
  { content: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
  { content: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { content: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { content: "We become what we think about.", author: "Earl Nightingale" },
  { content: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain" },
  { content: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { content: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { content: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { content: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { content: "The only thing standing between you and your goal is the story you keep telling yourself.", author: "Jordan Belfort" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { content: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { content: "The real test is not whether you avoid this failure, but whether you let it harden or shame you into inaction.", author: "Robert F. Kennedy" },
  { content: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { content: "In the end, we only regret the chances we didn't take.", author: "Lewis Carroll" },
  { content: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { content: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { content: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { content: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { content: "When you have a dream, you've got to grab it and never let go.", author: "Carol Burnett" },
  { content: "The only time you should ever look back is to see how far you've come.", author: "Unknown" },
  { content: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { content: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "It's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { content: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { content: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { content: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
  { content: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", author: "Roy T. Bennett" },
  { content: "I learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { content: "Do what you feel in your heart to be right, for you'll be criticized anyway.", author: "Eleanor Roosevelt" },
  { content: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { content: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { content: "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.", author: "Ray Goforth" },
  { content: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { content: "Your limitation—it's only your imagination.", author: "Unknown" },
  { content: "Great things never come from comfort zones.", author: "Unknown" },
  { content: "Dream it. Wish it. Do it.", author: "Unknown" },
  { content: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
  { content: "The harder you work, the luckier you get.", author: "Gary Player" },
  { content: "Dream bigger. Do bigger.", author: "Unknown" },
  { content: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { content: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { content: "Do something today that your future self will thank you for.", author: "Unknown" },
  { content: "Little things make big days.", author: "Unknown" },
  { content: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { content: "Don't downgrade your dream just to fit your reality. Upgrade your conviction to match your destiny.", author: "Stuart Scott" },
  { content: "You are what you do, not what you say you'll do.", author: "Carl Jung" },
  { content: "Magic is believing in yourself. If you can do that, you can make anything happen.", author: "Johann Wolfgang von Goethe" },
  { content: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { content: "It is never too late to be what you might have been.", author: "George Eliot" },
  { content: "You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
  { content: "The only person you should try to be better than is who you were yesterday.", author: "Unknown" },
  { content: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { content: "You're one step closer than you were yesterday.", author: "Unknown" },
  { content: "Make each day your masterpiece.", author: "John Wooden" },
  { content: "Where there is no struggle, there is no strength.", author: "Oprah Winfrey" },
  { content: "You didn't come this far to only come this far.", author: "Unknown" },
  { content: "The struggle you're in today is developing the strength you need tomorrow.", author: "Robert Tew" },
  { content: "Be so good they can't ignore you.", author: "Steve Martin" },
  { content: "Work hard in silence, let your success be the noise.", author: "Frank Ocean" },
  { content: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { content: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller Jr." },
  { content: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { content: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { content: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { content: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { content: "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.", author: "Joel Brown" },
  { content: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { content: "I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { content: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { content: "You have to expect things of yourself before you can do them.", author: "Michael Jordan" },
  { content: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { content: "I've failed over and over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
  { content: "The key is not the will to win. Everybody has that. It is the will to prepare to win that is important.", author: "Bobby Knight" },
  { content: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { content: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { content: "We need to give each other the space to grow, to be ourselves, to exercise our diversity.", author: "Max de Pree" },
  { content: "The only real mistake is the one from which we learn nothing.", author: "Henry Ford" },
  { content: "A journey of a thousand miles must begin with a single step.", author: "Lao Tzu" },
  { content: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
  { content: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl" },
  { content: "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends.", author: "Aristotle" },
  { content: "The unexamined life is not worth living.", author: "Socrates" },
  { content: "Happiness depends upon ourselves.", author: "Aristotle" },
  { content: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { content: "We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world.", author: "Buddha" },
  { content: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { content: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { content: "The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own.", author: "Lao Tzu" },
  { content: "A leader is best when people barely know he exists. When his work is done, his aim fulfilled, they will say: we did it ourselves.", author: "Lao Tzu" },
  { content: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Lao Tzu" },
  { content: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu" },
  { content: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { content: "The wise man adapts himself to circumstances, as water shapes itself to the vessel that contains it.", author: "Chinese Proverb" },
  { content: "He who asks a question is a fool for five minutes; he who does not ask a question remains a fool forever.", author: "Chinese Proverb" },
  { content: "A gem cannot be polished without friction, nor a man perfected without trials.", author: "Chinese Proverb" },
  { content: "The man who moves a mountain begins by carrying away small stones.", author: "Chinese Proverb" },
  { content: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { content: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
  { content: "Wherever you go, go with all your heart.", author: "Confucius" },
  { content: "The man who says he can and the man who says he can't are both correct.", author: "Confucius" },
  { content: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { content: "Well begun is half done.", author: "Aristotle" },
  { content: "Patience is bitter, but its fruit is sweet.", author: "Aristotle" },
  { content: "Pleasure in the job puts perfection in the work.", author: "Aristotle" },
  { content: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { content: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { content: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { content: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { content: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde" },
  { content: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
  { content: "The only way to get rid of a temptation is to yield to it.", author: "Oscar Wilde" },
  { content: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { content: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
  { content: "It is our choices that show what we truly are, far more than our abilities.", author: "J.K. Rowling" },
  { content: "It does not do to dwell on dreams and forget to live.", author: "J.K. Rowling" },
  { content: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", author: "J.K. Rowling" },
  { content: "The truth. It is a beautiful and terrible thing, and should therefore be treated with great caution.", author: "J.K. Rowling" },
  { content: "To the well-organized mind, death is but the next great adventure.", author: "J.K. Rowling" },
  { content: "Do or do not. There is no try.", author: "Yoda" },
  { content: "Fear is the path to the dark side.", author: "Yoda" },
  { content: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { content: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
  { content: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { content: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi" },
  { content: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { content: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { content: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr." },
  { content: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
  { content: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr." },
  { content: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
  { content: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
  { content: "Life's most persistent and urgent question is, what are you doing for others?", author: "Martin Luther King Jr." },
  { content: "I have decided to stick with love. Hate is too great a burden to bear.", author: "Martin Luther King Jr." },
  { content: "Nothing in the world is more dangerous than sincere ignorance and conscientious stupidity.", author: "Martin Luther King Jr." },
  { content: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
  { content: "We must accept finite disappointment, but never lose infinite hope.", author: "Martin Luther King Jr." },
  { content: "Love is the only force capable of transforming an enemy into a friend.", author: "Martin Luther King Jr." },
  { content: "Freedom is never voluntarily given by the oppressor; it must be demanded by the oppressed.", author: "Martin Luther King Jr." },
  { content: "A genuine leader is not a searcher for consensus but a molder of consensus.", author: "Martin Luther King Jr." },
  { content: "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge.", author: "Martin Luther King Jr." },
  { content: "Intelligence plus character—that is the goal of true education.", author: "Martin Luther King Jr." },
  { content: "Rarely do we find men who willingly engage in hard, solid thinking. There is an almost universal quest for easy answers.", author: "Martin Luther King Jr." },
  { content: "We may have different religions, different languages, different colored skin, but we all belong to one human race.", author: "Kofi Annan" },
  { content: "To live is to choose. But to choose well, you must know who you are and what you stand for.", author: "Kofi Annan" },
  { content: "Knowledge is power. Information is liberating.", author: "Kofi Annan" },
  { content: "We need to keep hope alive and strive to do better.", author: "Kofi Annan" },
  { content: "More than ever before in human history, we share a common destiny.", author: "Kofi Annan" },
  { content: "There is no passion to be found playing small—in settling for a life that is less than the one you are capable of living.", author: "Nelson Mandela" },
  { content: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { content: "A good head and a good heart are always a formidable combination.", author: "Nelson Mandela" },
  { content: "For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.", author: "Nelson Mandela" },
  { content: "May your choices reflect your hopes, not your fears.", author: "Nelson Mandela" },
  { content: "I never lose. I either win or learn.", author: "Nelson Mandela" },
  { content: "What counts in life is not the mere fact that we have lived. It is what difference we have made to the lives of others.", author: "Nelson Mandela" },
  { content: "After climbing a great hill, one only finds that there are many more hills to climb.", author: "Nelson Mandela" },
  { content: "Lead from the back—and let others believe they are in front.", author: "Nelson Mandela" },
  { content: "I am the master of my fate, I am the captain of my soul.", author: "William Ernest Henley" },
  { content: "Out of the night that covers me, Black as the pit from pole to pole, I thank whatever gods may be For my unconquerable soul.", author: "William Ernest Henley" },
  { content: "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", author: "Robert Frost" },
  { content: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { content: "The woods are lovely, dark and deep. But I have promises to keep, And miles to go before I sleep.", author: "Robert Frost" },
  { content: "Freedom lies in being bold.", author: "Robert Frost" },
  { content: "Poetry is when an emotion has found its thought and the thought has found words.", author: "Robert Frost" },
  { content: "The best way out is always through.", author: "Robert Frost" },
  { content: "Home is the place where, when you have to go there, they have to take you in.", author: "Robert Frost" },
  { content: "Love is an irresistible desire to be irresistibly desired.", author: "Robert Frost" },
  { content: "A poem begins as a lump in the throat.", author: "Robert Frost" },
  { content: "The world is full of willing people; some willing to work, the rest willing to let them.", author: "Robert Frost" },
  { content: "Nothing gold can stay.", author: "Robert Frost" },
  { content: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { content: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { content: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { content: "Success is not to be pursued; it is to be attracted by the person you become.", author: "Jim Rohn" },
  { content: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn" },
  { content: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
  { content: "We must all suffer from one of two pains: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { content: "If you don't design your own life plan, chances are you'll fall into someone else's plan.", author: "Jim Rohn" },
  { content: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn" },
  { content: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { content: "The same wind blows on us all. The difference in arrival is not the blowing of the wind, but the set of the sail.", author: "Jim Rohn" },
  { content: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { content: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { content: "You are the average of the five people you spend the most time with.", author: "Jim Rohn" },
  { content: "Learn to be happy with what you have while you pursue all that you want.", author: "Jim Rohn" },
  { content: "The major key to your better future is you.", author: "Jim Rohn" },
  { content: "Give whatever you are doing and whoever you are with the gift of your attention.", author: "Jim Rohn" },
  { content: "Success is doing ordinary things extraordinarily well.", author: "Jim Rohn" },
  { content: "You cannot change your destination overnight, but you can change your direction overnight.", author: "Jim Rohn" },
  { content: "The challenge of leadership is to be strong, but not rude; be kind, but not weak; be bold, but not bully.", author: "Jim Rohn" },
  { content: "Let others lead small lives, but not you. Let others argue over small things, but not you.", author: "Jim Rohn" }
];
